---

###
# TABLEAU
###

# Version
tableau_version_major: 2019
tableau_version_minor: 2
tableau_version_patch: 1

# RedHat
tableau_rpm_package: "tableau-server-{{ tableau_version_major }}-{{ tableau_version_minor }}-{{ tableau_version_patch }}.x86_64.rpm"
tableau_url_rpm: "https://downloads.tableau.com/tssoftware/{{ tableau_rpm_package }}"

# Postgres
tableau_postgresql_odbc_package: tableau-postgresql-odbc-09.06.0500-1.x86_64.rpm
tableau_postgresql_odbc_rpm: "https://downloads.tableau.com/drivers/linux/yum/tableau-driver/{{ tableau_postgresql_odbc_package }}"


tableau_fix_systemd_unit: false
# User
tableau_user: tabadmin
tableau_password: TabAdmin
tableau_password_encrypted: "$1$oDZkn1lx$LHyrdsUmcroVfQccsaEng/"

# Configuration
tableau_data_dir: /var/opt/tableau/tableau_server
tsm_packages: "/opt/tableau/tableau_server/packages"
tsm_data_dir: /opt/tableau/tsm
tsm_execute_args: "--accepteula"
tsm_licence: ""
tsm_registration:
  zip: 30004
  country: USA
  city: Alpharetta
  last_name: Patole
  industry: Software
  eula: yes
  title: Software Applications Engineer
  phone: 9561095800
  company: myowncloud
  state: GA
  department: Engineering
  first_name: Amit
  email: amitpatole@myowncloud.us
tsm_identity_store_type: local

tsm_deploy_examples: false

tabcmd_admin_username: admin
tabcmd_admin_password: admin12345

# Ssl
tableau_setup_ssl_helper: false
tableau_ssl_certs_dir: "/etc/tableaussl/"
tableau_ssl_key_ext: ".key.pem"
tableau_ssl_key_ext: ".crt"
